### ISSUE TITLE
Non constant memory during parsing

### ISSUE THREAD

**Issue by amarao** [technige/jsonstream#1]
jsonstream 0.9 consume non-constant memory during parsing of many small objects.

Steps to reproduce:

create large file of small json objects, f.e.:

```
[
    {"a1":"11","a2":"12","a3":"13" },
    {"a1":"21","a2":"22","a3":"23" },
    {"a1":"31","a2":"32","a3":"33" }
]
```

(~100000K of them).

following code:

```
from jsonstream import JSONStream
import sys

for o in JSONStream(sys.stdin):
    print(o)
```

Run cat sample.json|./sample.py

Memory for python process will starts to grow. In my tests it grow over 300Mb for 118Mb JSON.

**Comment by technige** [comment]
Good spot. This looks to be down to a failure to clean up data that has already been read. Currently looking at a fix.

**Comment by technige** [comment]
Are you able to test the latest code in master? This should in theory address the problem you've identified so it will be great to get confirmation before release.

**Comment by amarao** [comment]
I ran tests with code from master (0.9.1) and it gulps 1.8Gb JSON with merely 4.7Mb of res. And no growth at all.  It really works!

Thank you!

P. S. You should update pypi package info, it points to you site as home page, and home page say nothing about jsonstream.

**Comment by technige** [comment]
Good to know, thanks for testing so quickly. I'll release a new version shortly.

You're right about the URL on PyPI but I'm planning to move documentation onto my site so it'll be up to date again soon.
